version: "3.8"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./funeralwishes:/usr/local/apache2/htdocs/funeralwishes
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./funeralwishes:/usr/local/apache2/htdocs/funeralwishes
    working_dir: /usr/local/apache2/htdocs/funeralwishes
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: docker_laravel
      MYSQL_USER: test
      MYSQL_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

