version: '3'

services:
  web:
    build:
      context: php
    ports: 
      - '8000:80'
    volumes:
      - ./php:/var/www/html/
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
